services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - .data:/data/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    restart: always

  # nextjs:
  #   container_name: nextjs
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "3000:1337"

  # strapi:
  #   container_name: strapi
  #   build:
  #     context: ./cms
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "1337:1337"
  #   restart: always
  #   depends_on:
  #     - postgres
